from docx import Document
from docx.shared import Pt
from io import BytesIO
import re

def generate_docx(summary_text, translation_text=None, target_language="Chinese"):
    """
    Generates a Word document from the summary and translation text.
    Handles basic Markdown formatting like headers and bullet points.
    
    Args:
        summary_text (str): The English summary in Markdown format.
        translation_text (str): The translated summary in Markdown format.
        target_language (str): The target language of the translation.
        
    Returns:
        bytes: The generated .docx file as a byte stream.
    """
    doc = Document()
    
    # --- Style Settings ---
    # You could customize fonts here if needed, but defaults are usually fine for MVP
    
    # --- Helper: Process Markdown-ish text ---
    def process_content(parent, title, text):
        if not text or not text.strip():
            return
            
        parent.add_heading(title, level=1)
        
        # Split text into blocks (paragraphs or headers)
        lines = text.strip().split('\n')
        for line in lines:
            line = line.strip()
            if not line:
                continue
            
            # Handle Headings (English or Chinese)
            if line.startswith('# '):
                parent.add_heading(line[2:], level=2)
            elif line.startswith('## '):
                parent.add_heading(line[3:], level=3)
            elif line.startswith('### '):
                parent.add_heading(line[4:], level=4)
            # Handle Bullet Points
            elif line.startswith('* ') or line.startswith('- '):
                # Simple bullet point
                content = line[2:].strip()
                # Handle bolding inside bullets (Basic: **text**)
                p = parent.add_paragraph(style='List Bullet')
                _add_formatted_text(p, content)
            else:
                # Normal paragraph
                p = parent.add_paragraph()
                _add_formatted_text(p, line)

    def _add_formatted_text(paragraph, text):
        """Very basic bolding support for **text**"""
        parts = re.split(r'(\*\*.*?\*\*)', text)
        for part in parts:
            if part.startswith('**') and part.endswith('**'):
                run = paragraph.add_run(part[2:-2])
                run.bold = True
            else:
                paragraph.add_run(part)

    # --- Document Construction ---
    # Add Main Title
    doc.add_heading('DocuMind Analysis Report', 0)
    
    # Add Summary Section
    process_content(doc, 'English Summary', summary_text)
    
    # Add Translation Section
    if translation_text and translation_text.strip():
        doc.add_page_break()
        process_content(doc, f'{target_language} Translation', translation_text)
        
    # Add Footer-like info
    doc.add_paragraph()
    footer_p = doc.add_paragraph('Generated by DocuMind MVP')
    footer_p.alignment = 1 # Center
    
    # Save to buffer
    buffer = BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.getvalue()
