"""
fyp_test_runner.py — FYP Document Parsing System Test Script
============================================================
This script is used to test the newly integrated OCR & document parsing system.
Based on the original test_runner.py design.

Usage:
    & "C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\python.exe" fyp_test_runner.py

Features:
    - Supports PDF, DOCX, PPTX, PNG, JPG, etc.
    - Mimics Streamlit UploadedFile environment.
    - Generates Markdown reports with timing and character stats.
"""

import os
import sys
import time
import io
import logging
from pathlib import Path
from datetime import datetime

# ── Compatibility Patch (for Python 3.9) ───────────────────────────────────
if sys.version_info < (3, 10):
    try:
        import importlib_metadata
        import importlib.metadata
        if not hasattr(importlib.metadata, 'packages_distributions'):
            importlib.metadata.packages_distributions = importlib_metadata.packages_distributions
    except ImportError:
        pass

# ── Windows Console UTF-8 Support ──────────────────────────────────────────
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

# ─────────────────────────────────────────────────────────────────────────────
# ★ Hardcoded Configuration
# ─────────────────────────────────────────────────────────────────────────────
INPUT_FILE = r"C:\Users\User\Desktop\fyp\data_test\L3_Computer_Crimes_2025 (1).pptx"   
OUTPUT_DIR = r"C:\Users\User\Desktop\fyp_test_results" 
ROCKET_MODE = False                                   
# ─────────────────────────────────────────────────────────────────────────────

def _setup_logging():
    """Configure logging format to match original test_runner.py style"""
    root = logging.getLogger()
    root.handlers = []
        
    root.setLevel(logging.INFO)
    handler = logging.StreamHandler(sys.stdout)
    handler.setFormatter(
        logging.Formatter(
            fmt="%(asctime)s  [%(levelname)-8s]  %(name)s  →  %(message)s",
            datefmt="%H:%M:%S",
        )
    )
    root.addHandler(handler)

def _check_environment():
    """Environment check to warn if wrong Python is used (e.g. Inkscape)"""
    python_exe = sys.executable
    if "Inkscape" in python_exe or "Microsoft\\WindowsApps" in python_exe:
        print("\n" + "!"*60)
        print(" [WARNING] Potential incomplete Python environment detected!")
        print(f" Current Path: {python_exe}")
        print(" This may lead to 'ModuleNotFoundError' (fitz, paddleocr, etc.).")
        print(" Please use the project's Python 3.9 environment:")
        print(" & \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\python.exe\" fyp_test_runner.py")
        print("!"*60 + "\n")
        return False
    return True

class MockUploadedFile(io.BytesIO):
    """Mock Streamlit UploadedFile object"""
    def __init__(self, file_path):
        with open(file_path, 'rb') as f:
            content = f.read()
        super().__init__(content)
        self.name = os.path.basename(file_path)
        self.size = len(content)

def _write_report(file_name, raw_text, elapsed, report_path):
    """Generate Markdown report"""
    lines = [
        f"# Parsing Test Report: {file_name}",
        f"",
        f"- **Timestamp**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"- **Elapsed Time**: {elapsed:.3f} s",
        f"- **Characters**: {len(raw_text)}",
        f"- **Mode**: {'Rocket' if ROCKET_MODE else 'Standard'}",
        f"",
        "---",
        "## Extracted Content Preview",
        f"",
        raw_text,
        f"",
        "---",
        "*Report generated by fyp_test_runner.py*"
    ]
    
    Path(report_path).parent.mkdir(parents=True, exist_ok=True)
    with open(report_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Report saved: {report_path}")

def main():
    _setup_logging()
    _check_environment()
    logger = logging.getLogger("FYP_Test")

    input_path = Path(INPUT_FILE)
    if not input_path.exists():
        print(f"\n[ERROR] Input file not found: {INPUT_FILE}")
        print("Tip: Please update the INPUT_FILE path in the script.")
        return

    print("="*60)
    print("  FYP Document Parsing Engine - Testing".center(60))
    print("="*60)
    print(f" File     : {input_path.name}")
    print(f" Mode     : {'Rocket' if ROCKET_MODE else 'Standard'}")
    print("-"*60)

    try:
        from ocr_engine import extract_text_from_image
    except ImportError as e:
        print(f"[CRITICAL] Failed to import ocr_engine: {e}")
        print("Ensure you run this script from the project root.")
        return

    # 1. Mock upload
    print(f"[1/3] Loading file and mocking upload...")
    mock_file = MockUploadedFile(INPUT_FILE)

    # 2. Execute parsing
    print(f"[2/3] Starting engine ({input_path.suffix.upper()})...")
    start_time = time.perf_counter()
    
    raw_text = extract_text_from_image(mock_file, fast_mode=ROCKET_MODE)
    
    elapsed = time.perf_counter() - start_time

    # 3. Summary
    print(f"[3/3] Parsing finished! Time: {elapsed:.2f}s")
    
    if "⚠️" in raw_text:
        print(f"\n[Detected Warnings/Errors]:\n{raw_text}")
    else:
        print(f"\n[Success] Characters extracted: {len(raw_text)}")
        
        # Preview
        preview = raw_text[:300] + "..." if len(raw_text) > 300 else raw_text
        print("-" * 30 + " Preview " + "-" * 30)
        print(preview)
        print("-" * 70)

        # Write report
        report_name = f"{input_path.stem}_fyp_test.md"
        report_path = Path(OUTPUT_DIR) / report_name
        _write_report(input_path.name, raw_text, elapsed, report_path)

    print("\nTest Finished.")

if __name__ == "__main__":
    main()
